# for rest client extention - ext should be .rest to work
GET http://localhost:8000/user
###
POST http://localhost:8000/user 
Content-Type: application/json

{
    "name":"moon knight",
    "email":"MOON_9eight@gmail.com",
    "image":"moon_image"
}
###
POST http://localhost:8000/user 
Content-Type: application/json

{
    "name": "Bruce Wayne",
    "email": "batman@wayneenterprises.com",
    "image": "🦇🌃 Gotham's Dark Knight"
}
### 
GET http://localhost:8000/post
###
POST http://localhost:8000/post 
Content-Type: application/json

{
    "postText":"Sample Post Msg", 
    "createdAt":"326347347", 
    "createdBy":"6596e7e039f59629cd43289e", 
    "imageUrl":"SampleUrl"
}
###
POST http://localhost:8000/post 
Content-Type: application/json

{
    "postText":"welcome to Alabama", 
    "createdAt":"09112001", 
    "createdBy":"6596e7e039f59629cd43289e", 
    "imageUrl":"TwinTower"
}
###
POST http://localhost:8000/post 
Content-Type: application/json

{
    "postText":"welcome to Germany", 
    "createdAt":"20041889", 
    "createdBy":"66167c7572c435743b8b2f34"
}

###
GET http://localhost:8000/user/wami50731@gmail.com
###
POST http://localhost:8000/post 
Content-Type: application/json

{
    "postText":"welcome to Germany", 
    "createdAt":"20041889", 
    "createdBy":"66167c7572c435743b8b2f34",
    "imageUrl":"YouKnow..."
}

### just testing...
POST http://localhost:8000/post 
Content-Type: application/json
###
PUT http://localhost:8000/post/like/661d0f61ea7dfe5d16c32e9a
Content-Type: application/json

{
    "userId":"66167c7572c435743b8b2f34",
    "isLike":true
}
###
PUT http://localhost:8000/post/like/661d0f61ea7dfe5d16c32e9a
Content-Type: application/json

{
    "userId":"khushaltest",
    "isLike":true
}
###
